<?php /** @var \Magento\Framework\View\Element\Template $block */ ?>
<div id="shipping-plan" data-bind="scope: 'skuLookup'">
    <div id="sku-lookup">
        <!-- ko template: getTemplate() --><!-- /ko -->
    </div>
</div>

<script type="text/x-magento-init">
    {
        "#shipping-plan": {
            "Magento_Ui/js/core/app": <?= $block->getJsLayout() ?>
        }
    }
</script>